version: '3.8'

services:
  product-search-service:
    build: .
    ports:
      - '5002:5002'
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=False
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-product-search
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.listen-address=0.0.0.0:9090'
    ports:
      - '9092:9090' # Puerto externo 9092 mapeado al interno 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - product-search-service

volumes:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
